### ISSUE TITLE
Why is this function used

### ISSUE THREAD

**Issue by acute9** [BosonLabs/STASIS#30]
https://github.com/BosonLabs/STASIS/blob/06c7371235d9b7abdacac77c092034399627a8aa/SmartContracts/PAI.sol#L378

**Comment by Prabhakaran1998** [comment]
The Address Library intends to make address function calls safely, and This function **_functionCallWithValue** allows address function calls to be made safely. And this line of function code is updated to another version. Here is the updated code:                                     https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol

**Comment by ELEMENTFI** [comment]
closed.
