### ISSUE TITLE
"Amount must be less than total Tester3"  What is tester3?

### ISSUE THREAD

**Issue by acute9** [BosonLabs/STASIS#31]
https://github.com/BosonLabs/STASIS/blob/06c7371235d9b7abdacac77c092034399627a8aa/SmartContracts/PAI.sol#L730

**Comment by Prabhakaran1998** [comment]
**Tester3**  denotes the _rTotal value.
Tester3 is a word to denote _rTotal, In reflect finance and yieldpandas word **reflection** is used to denote _rTotal Value. The below Line of code is used in Reflect finance and yield pandas,                                  
                 require(rAmount <= _rTotal, "Amount must be less than total reflections");

**Comment by ELEMENTFI** [comment]
closing this issue.
